#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


SOURCE_COMMIT = "b2987c1211e745aa9dc99db94e0ad7eb73cc11e4"
SOURCE_SHA256 = "89dc043cd330066b40353b8c45bd7f9d0c7fc7a1e9afe1bf1233a0c751c7d3b0"
STANDARD_IDS = (
    "sw-dev-security-49",
    "cwe-top-25-2025",
    "owasp-top-10-2025",
    "owasp-asvs-5",
    "owasp-proactive-controls",
    "sw-dev-security-7-types",
    "kisa-secure-coding-guide",
)


def _labels(value: object) -> dict[str, str]:
    if not isinstance(value, dict) or not all(isinstance(value.get(key), str) for key in ("en", "ko")):
        raise RuntimeError("standard catalog requires English and Korean labels")
    return {"en": value["en"], "ko": value["ko"]}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the compact MCP standards catalog")
    parser.add_argument("source_root", type=Path, help="KODA security source checkout")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src/koda_mcp/standard_catalog_data.py",
    )
    args = parser.parse_args()

    source_file = args.source_root / "platforms/shared/python/security_scanner/standards.py"
    if hashlib.sha256(source_file.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise RuntimeError("standards.py does not match the pinned audited source")

    sys.path.insert(0, str(args.source_root / "platforms/shared/python"))
    from security_scanner.standards import rule_standard_mappings_payload, standards_payload

    core_root = Path(__file__).resolve().parents[1] / "src/koda_core"
    copied_core = "\n".join(path.read_text(encoding="utf-8") for path in core_root.rglob("*.py"))
    standards = {}
    for standard in standards_payload():
        standard_id = standard["id"]
        if standard_id not in STANDARD_IDS:
            continue
        standards[standard_id] = {
            "standard_id": standard_id,
            "labels": _labels(standard["labels"]),
            "issuer": _labels(standard["issuer"]),
            "published_on": standard["published_on"],
            "version": standard["version"],
            "references": [
                {"labels": _labels(reference["labels"]), "url": reference["url"]}
                for reference in standard["references"]
            ],
        }

    mappings = {}
    priority = {standard_id: index for index, standard_id in enumerate(STANDARD_IDS)}
    for rule_id, source_mappings in rule_standard_mappings_payload().items():
        if rule_id not in copied_core:
            continue
        normalized = []
        seen = set()
        for item in source_mappings:
            standard_id = item["standard_id"]
            if standard_id not in priority:
                continue
            control_id = item.get("control_id")
            criterion_id = item.get("official_id") or item["category_id"]
            key = (standard_id, item["category_id"], control_id, criterion_id)
            if key in seen:
                continue
            seen.add(key)
            normalized.append(
                {
                    "standard_id": standard_id,
                    "criterion_id": criterion_id,
                    "criterion_labels": _labels(item.get("control_title") or item["category_labels"]),
                    "mapping_kind": "direct_control" if control_id else "related_category",
                    "category_id": item["category_id"],
                    "category_labels": _labels(item["category_labels"]),
                    "control_id": control_id,
                    "guide_id": item.get("guide_id"),
                    "cwe_ids": item.get("cwe_ids", []),
                    "support_level": item.get("support_level"),
                }
            )
        if normalized:
            mappings[rule_id] = tuple(
                sorted(
                    normalized,
                    key=lambda item: priority[item["standard_id"]],
                )
            )

    payload = json.dumps(
        {"standards": standards, "mappings": mappings},
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    rendered = (
        "# Generated by scripts/sync_standard_catalog.py; do not edit manually.\n"
        "import json as _json\n"
        f"SOURCE_COMMIT = {SOURCE_COMMIT!r}\n"
        f"SOURCE_SHA256 = {SOURCE_SHA256!r}\n"
        f"STANDARD_ORDER = {STANDARD_IDS!r}\n"
        f"_DATA = _json.loads({payload!r})\n"
        "STANDARD_REFERENCES = _DATA['standards']\n"
        "RULE_STANDARD_MAPPINGS = _DATA['mappings']\n"
        "del _DATA\n"
    )
    args.output.write_text(rendered, encoding="utf-8")
    print(f"generated {args.output}: {len(mappings)} rules, {sum(map(len, mappings.values()))} mappings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
